---
# tasks file for splunk_server
- name: add tag to instance
  ec2_tag:
    resource: '{{ item.id }}'
    region: "{{ ec2_region }}"
    state: present
  with_items: '{{ ec2.instances }}'
  args:
    tags:
      Name: splunkserver
